name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: update_ubuntu
      shell: bash 
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev lld libudev-dev
      
    - name: build
      run: make build
      
    - name: test
      run: make test
